# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/discovery.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/discovery.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16protos/discovery.proto\"r\n\x10\x44iscoveryMessage\x12\x33\n\x0cmessage_type\x18\x01 \x01(\x0e\x32\x1d.DiscoveryMessage.MessageType\")\n\x0bMessageType\x12\r\n\tDISCOVERY\x10\x00\x12\x0b\n\x07\x43ONNECT\x10\x01\x62\x06proto3')
)



_DISCOVERYMESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='DiscoveryMessage.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCOVERY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=99,
  serialized_end=140,
)
_sym_db.RegisterEnumDescriptor(_DISCOVERYMESSAGE_MESSAGETYPE)


_DISCOVERYMESSAGE = _descriptor.Descriptor(
  name='DiscoveryMessage',
  full_name='DiscoveryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='DiscoveryMessage.message_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DISCOVERYMESSAGE_MESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=140,
)

_DISCOVERYMESSAGE.fields_by_name['message_type'].enum_type = _DISCOVERYMESSAGE_MESSAGETYPE
_DISCOVERYMESSAGE_MESSAGETYPE.containing_type = _DISCOVERYMESSAGE
DESCRIPTOR.message_types_by_name['DiscoveryMessage'] = _DISCOVERYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiscoveryMessage = _reflection.GeneratedProtocolMessageType('DiscoveryMessage', (_message.Message,), dict(
  DESCRIPTOR = _DISCOVERYMESSAGE,
  __module__ = 'protos.discovery_pb2'
  # @@protoc_insertion_point(class_scope:DiscoveryMessage)
  ))
_sym_db.RegisterMessage(DiscoveryMessage)


# @@protoc_insertion_point(module_scope)
