# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/chain.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/chain.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12protos/chain.proto\"\x17\n\x05\x43hain\x12\x0e\n\x06\x62locks\x18\x01 \x03(\x0c\x62\x06proto3')
)




_CHAIN = _descriptor.Descriptor(
  name='Chain',
  full_name='Chain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blocks', full_name='Chain.blocks', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=45,
)

DESCRIPTOR.message_types_by_name['Chain'] = _CHAIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chain = _reflection.GeneratedProtocolMessageType('Chain', (_message.Message,), dict(
  DESCRIPTOR = _CHAIN,
  __module__ = 'protos.chain_pb2'
  # @@protoc_insertion_point(class_scope:Chain)
  ))
_sym_db.RegisterMessage(Chain)


# @@protoc_insertion_point(module_scope)
