# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/request.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x14protos/request.proto\"F\n\x07Request\x12\"\n\x0crequest_type\x18\x01 \x01(\x0e\x32\x0c.RequestType\x12\x17\n\x0frequest_message\x18\x02 \x01(\x0c\".\n\x0b\x42lobMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0c\n\x04\x62lob\x18\x02 \x01(\x0c\"6\n\x11MinedBlockMessage\x12\x12\n\nchain_cost\x18\x01 \x01(\r\x12\r\n\x05\x62lock\x18\x02 \x01(\x0c\"#\n\x10\x44iscoveryMessage\x12\x0f\n\x07node_id\x18\x01 \x01(\x07*A\n\x0bRequestType\x12\x08\n\x04\x42LOB\x10\x00\x12\t\n\x05\x41LIVE\x10\x01\x12\x0f\n\x0bMINED_BLOCK\x10\x02\x12\x0c\n\x08\x44ISOVERY\x10\x03\x62\x06proto3')
)

_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BLOB', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALIVE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MINED_BLOCK', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISOVERY', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=237,
  serialized_end=302,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTYPE)

RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
BLOB = 0
ALIVE = 1
MINED_BLOCK = 2
DISOVERY = 3



_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_type', full_name='Request.request_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_message', full_name='Request.request_message', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=94,
)


_BLOBMESSAGE = _descriptor.Descriptor(
  name='BlobMessage',
  full_name='BlobMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='BlobMessage.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blob', full_name='BlobMessage.blob', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=142,
)


_MINEDBLOCKMESSAGE = _descriptor.Descriptor(
  name='MinedBlockMessage',
  full_name='MinedBlockMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chain_cost', full_name='MinedBlockMessage.chain_cost', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block', full_name='MinedBlockMessage.block', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=198,
)


_DISCOVERYMESSAGE = _descriptor.Descriptor(
  name='DiscoveryMessage',
  full_name='DiscoveryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='DiscoveryMessage.node_id', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=235,
)

_REQUEST.fields_by_name['request_type'].enum_type = _REQUESTTYPE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['BlobMessage'] = _BLOBMESSAGE
DESCRIPTOR.message_types_by_name['MinedBlockMessage'] = _MINEDBLOCKMESSAGE
DESCRIPTOR.message_types_by_name['DiscoveryMessage'] = _DISCOVERYMESSAGE
DESCRIPTOR.enum_types_by_name['RequestType'] = _REQUESTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'protos.request_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)

BlobMessage = _reflection.GeneratedProtocolMessageType('BlobMessage', (_message.Message,), dict(
  DESCRIPTOR = _BLOBMESSAGE,
  __module__ = 'protos.request_pb2'
  # @@protoc_insertion_point(class_scope:BlobMessage)
  ))
_sym_db.RegisterMessage(BlobMessage)

MinedBlockMessage = _reflection.GeneratedProtocolMessageType('MinedBlockMessage', (_message.Message,), dict(
  DESCRIPTOR = _MINEDBLOCKMESSAGE,
  __module__ = 'protos.request_pb2'
  # @@protoc_insertion_point(class_scope:MinedBlockMessage)
  ))
_sym_db.RegisterMessage(MinedBlockMessage)

DiscoveryMessage = _reflection.GeneratedProtocolMessageType('DiscoveryMessage', (_message.Message,), dict(
  DESCRIPTOR = _DISCOVERYMESSAGE,
  __module__ = 'protos.request_pb2'
  # @@protoc_insertion_point(class_scope:DiscoveryMessage)
  ))
_sym_db.RegisterMessage(DiscoveryMessage)


# @@protoc_insertion_point(module_scope)
